title: Bifrost
author: Ditt navn
logo: logo.png

subtitle: En mikroskopisk tilnærming til fysikalsk kjemi

execute:
  execute_notebooks: auto

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/andreadh/bifrost
  path_to_book: docs
  branch: main

html:
  use_issues_button: false
  use_repository_button: false
  extra_css:
    - _static/custom.css

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath