title: Bifrost
author: Ditt navn
logo: logo.png

execute:
  execute_notebooks: cache
  timeout: 120
  allow_errors: false

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/andreasdh/bifrost
  path_to_book: docs
  branch: main

html:
  use_issues_button: false
  use_repository_button: false
  extra_css:
    - _static/custom.css

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
